name: tr_logger
description: Logger for Tron Energy Wallet
version: 1.0.0
homepage: https://tr.energy/
publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  logging: ^1.3.0

dev_dependencies:
  very_good_analysis: ^9.0.0

topics:
  - logger
